//随机背景图片数组,图片可以换成图床链接，注意最后一条后面不要有逗号
var backimg =[
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00004.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00013.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00015.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00019.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00021.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00025.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00027.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00028.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00029.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00031.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00032.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00040.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00041.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00042.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00043.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00045.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00057.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00059.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00075.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00080.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00090.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00091.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00095.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00103.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00106.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00107.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00117.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00118.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00121.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00127.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00133.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00134.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00142.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00167.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00168.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00175.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00176.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00178.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00180.webp)",
  "url(https://gitee.com/youthlql/randombg/raw/master/bg/00184.webp)"  
  ];
  //获取背景图片总数，生成随机数
  var bgindex =Math.ceil(Math.random() * (backimg.length-1));
  //重设背景图片
  document.getElementById("web_bg").style.backgroundImage = backimg[bgindex];
  //重设banner图片
  document.getElementById("page-header").style.backgroundImage = backimg[bgindex];
